### ISSUE TITLE
O que falta para quarta feira

### ISSUE THREAD

**Issue by julianoce** [gabihecksher/jupiter#1]
- [x] - Testar o Cond(speed-quick) 
- [x] - Criar o CSeq(speed-quick)
- [x] - Fazer a pilha de env e store
- [x] - Tirar os Anys (speed-quick)
- [x] - Fazer o Calc
- [x] - Tratar a inicializacao de variaveis
- [x] - Testar o fatorial

**Comment by julianoce** [comment]
o teste do while do fatorial funciona

**Comment by gabihecksher** [comment]
calc funcionando para operacoes sum, sub, mul e div, já retorna o resultado da expressao com as pilhas zeradas
